export const actions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CHANGE_NAME: 'CHANGE_NAME',
  UPDATE_TABLE_REMAINING: 'UPDATE_TABLE_REMAINING',
  SET_TABLES: 'SET_TABLES',
  SET_BOOKING_DATA: 'SET_BOOKING_DATA',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
};
